List<String> affirmations = [
  "Asking for help is a sign of self-respect and self-awareness.",
  "Changing my mind is a strength, not a weakness.",
  "Every decision I make is supported by my whole and inarguable experience.",
  "I affirm and encourage others, as I do myself.",
  "I alone hold the truth of who I am.",
  "I am allowed to ask for what I want and what I need.",
  "I am allowed to feel good.",
  "I am capable of balancing ease and effort in my life.",
  "I am complete as I am, others simply support me.",
  "I am content and free from pain",
  "I am doing the work that works for me",
  "I am good and getting better",
  "I am growing and I am going at my own pace",
  "I am held and supported by those who love me",
  "I am in charge of how I feel and I choose to feel happy",
  "I am listening and open to the messages the universe has to offer today",
  "I am loved and worthy",
  "I am more than my circumstances dictate",
  "I am open to healing",
  "I am optimistic because today is a new day",
  "I am peaceful and whole",
  "I am proof enough of who I am and what I deserve",
  "I am responsible for myself, and I start there",
  "I am safe and surrounded by love and support",
  "I am still learning so it’s okay to make mistakes",
  "I am understood and my perspective is important",
  "I am valued and helpful",
  "I am well-rested and excited for the day",
  "I am worthy of investing in myself",
  "I belong here, and I deserve to take up space",
  " I breath in healing, I exhale the painful things that burden my heart",
  "I breathe in trust, I exhale doubt",
  "I can be soft in my heart and firm in my boundaries",
  "I can control how I respond to things that are confronting",
  "I can hold two opposing feelings at once, it means I am processing",
  "I celebrate the good qualities in others and myself",
  "I deserve an affirming touch on my own terms",
  "I deserve information and I deserve moments of silence, too",
  "I deserve self-respect and a clean space",
  "I do all things in love",
  "I do not have to linger in dark places; there is help for me here",
  "I do not pretend to be anyone or anything other than who I am",
  "I do not rise and fall for another",
  "I do not rush through my life, I temper speed with stillness",
  "I embrace change seamlessly and rise to the new opportunity it presents",
  "I embrace the questions in my heart and welcome the answers in their own time",
  "I grow towards my interests, like a plant reaching for the sun",
  "I have come farther than I would have ever thought possible, and I’m learning along the way",
  "I have everything I need to succeed",
  "I hold community for others, and am held in community by others",
  "I hold wisdom beyond knowledge",
  "I invite abundance and a generous heart",
  "I invite art and music into my life",
  "I leave room in my life for spontaneity",
  "I let go of the things that sit achingly out of reach",
  "I look forward to tomorrow and the opportunities that await me",
  "I love that I love what I love",
  "I make decisions based on a good gut, I make changes based on a growing heart",
  "I make time to experience grief and sadness when necessary",
  "I nourish myself with kind words and joyful foods",
  "I practice gratitude for all that I have, and all that is yet to come",
  "I release the fears that do not serve me",
  "I respect the cycle of the seasons",
  "I seek out mystery in the ordinary",
  "I strive for joy, not for perfection",
  "I tell the truth about who I am and what I need from others",
  "I uplift my joy and the joy of others",
  "I welcome the wisdom that comes with growing older",
  "I welcome what is, I welcome what comes",
  "I will allow myself to evolve",
  "Letting go creates space for opportunities to come",
  "My body is beautiful in this moment and at its current size",
  "My body is worthy of being cared for and adorned in beautiful garments",
  "My feelings deserve names, deserve recognition, deserve to be felt",
  "My heart is open to helpfulness from myself and from others",
  "My heart knows its own way",
  "My life is not a race or competition",
  "My perspective is unique and important",
  "My pleasure does not require someone else’s pain",
  "My sensitivity is beautiful, and my feelings and emotions are valid",
  "My weirdness is wonderful",
  "Saying “no” is an act of self-affirmation, too",
  "Sometimes the work is resting",
  "There is growth in stillness",
  "There is peace in changing your mind when it is done in love",
  "There is poetry in everything, if I look for it",
  "There is room for me at the table",
  "There is something in this world that only I can do. That is why I am here",
  "There is strength in quiet, there is vulnerability in being loud",
  "Today I celebrate that I am younger than I’m ever going to be",
  "Today is an opportunity to grow and learn",
  "When I feel fear, I feed trust",
  "When I focus on my reason for being, I am infinitely brave",
  "When I forgive myself, I free myself",
  "When I release shame, I move into myself more beautifully",
  "When I root into the earth, the earth rises to support me",
  "When I speak my needs, I receive them abundantly",
  "When I talk to myself as I would a friend, I see all my best qualities and I allow myself to shine",
  "Words may shape me, but they do not make me. I am here already",
  "I am capable of achieving anything I set my mind to.",
  "I am worthy of love and respect.",
  "I choose to let go of all negativity and focus on the positive.",
  "I am confident in my abilities and decisions.",
  "I trust the path that life is taking me on.",
  "I am grateful for all the blessings in my life.",
  "I am resilient and can overcome any obstacle.",
  "I am worthy of success and happiness.",
  "I choose to live a life filled with joy and abundance.",
  "I am worthy of forgiveness and can forgive others with ease.",
  "I am deserving of a fulfilling and loving relationship.",
  "I am powerful and in control of my own life.",
  "I am always learning and growing as a person.",
  "I am capable of creating positive change in the world.",
  "I am worthy of self-care and taking time for myself.",
  "I trust in the universe and its plan for me.",
  "I am confident in expressing myself and my opinions.",
  "I am deserving of respect and kindness from others.",
  "I am filled with inner peace and tranquility.",
  "I am deserving of a life filled with purpose and passion.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe you can and you're halfway there.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "The only way to do great work is to love what you do.",
  "You miss 100% of the shots you don't take.",
  "It does not matter how slowly you go as long as you do not stop.",
  "You are not a drop in the ocean. You are the entire ocean in a drop.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Believe in the power of your dreams and the strength of your spirit.",
  "Your limitation—it's only your imagination.",
  "If you want to achieve greatness, stop asking for permission.",
  "Don't watch the clock; do what it does. Keep going.",
  "You don't have to be great to start, but you have to start to be great.",
  "The only person you are destined to become is the person you decide to be.",
  "The best way to predict your future is to create it.",
  "Chase your dreams until they become your reality.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Your time is limited, don't waste it living someone else's life.",
  "It always seems impossible until it's done.",
  "Strive not to be a success, but rather to be of value.",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
  "Believe and act as if it were impossible to fail.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.",
  "Do not wait for opportunities, create them.",
  "Everything you can imagine is real.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "You can't use up creativity. The more you use, the more you have.",
  "The only way to have a good day is to start it with a positive attitude.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  "You are the only one who can limit your greatness.",
];

List<String> quotesTitle = [
  "Get inspired!",
  "Boost your mood",
  "Positive vibes ahead",
  "Stay motivated",
  "Think positive thoughts",
  "Here's your pick-me-up",
  "Reminder to smile",
  "Today's dose of motivation",
  "Your inspiration for the day",
  "Unlock your potential",
  "Daily Inspiration",
  "Mental Boost",
  "Mindful Moment",
  "Stay Focused",
  "Words of Wisdom",
  "Motivational Minute",
  "Positive Energy",
  "You've Got This",
  "Encouraging Words",
  "Fuel for the Soul",
  "Mindset Reminder",
  "Think Happy Thoughts",
  "Be Inspired Today",
  "Small Wins Matter",
  "Self-Care Reminder",
  "Create Your Own Sunshine",
  "Believe in Yourself",
  "Rise and Shine",
  "One Day at a Time",
  "Find Your Inner Strength"
];
